---
docker_version: "latest"
docker_architecture: "{{ 'arm64' if ansible_machine == 'aarch64' else 'amd64' }}"
enable_docker_user_group: false
docker_daemon_config:
  debug: false
  log-driver: "json-file"
  log-opts:
    max-size: "10m"
    max-file: "3"
  storage-driver: overlay2
